source/source/urls.py
from django.contrib import admin
from django.shortcuts import redirect
from django.urls import include
from django.conf import settings
from django.conf.urls.static import static
from django.core.exceptions import PermissionDenied
from django.test import SimpleTestCase, override_settings
from django.urls import path


def response_error_handler(request, exception=None):
    return redirect('webapp:error_page')


def permission_denied_view(request):
    raise PermissionDenied


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('webapp.urls')),
    path('auth/', include('django.contrib.auth.urls')),
    path('select2/', include('django_select2.urls')),
    path('403/', permission_denied_view),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

handler403 = response_error_handler


@override_settings(ROOT_URLCONF=__name__)
class CustomErrorHandlerTests(SimpleTestCase):

    def test_handler_renders_template_response(self):
        response = self.client.get('/403/')
        self.assertContains(response, 'Error handler content', status_code=403)

source/webapp/urls.py
from django.urls import path
from webapp.MySQL_to_Word.homework_word import create_word_homework
from webapp.MySQL_to_Word.program_word import create_word_program
from webapp.views.skils import SkillDetailView, SkillUpdateView, SkillCreateView, SkillSearchView, delete_skill
from webapp.views.child import ChildList, ChildSearchView, ChildDetailView, ChildUpdateView, ChildCreateView, \
    soft_delete_child
from webapp.views.program import ProgramDetailView, ProgramListView, ProgramCreateView, ProgramUpdateView, \
    ProgramSearchView, AddSkillInProgram, SkillInProgramUpdate, soft_delete_program
from webapp.views.categories import CategoriesListView, CategoriesDetailView, CategoriesCreateView, \
    CategoriesUpdateView, CategoriesSearchView
from webapp.views.session import create_session_and_result, counter_get_view, counter_done, \
    counter_done_with_hint, cancel_session
from webapp.views.result import change_status_skill, ResultListView, close_session_result_view
from webapp.views.main_page import MainListView
from webapp.views.users import register, UserDetailView, UserListView, user_update, soft_delete_user, \
    user_password_update
from webapp.MySQL_to_Excel.sheet import create_excel_file
from webapp.views.testing import CreateTesting, StartTesting, update_result_level, update_result_status, \
    update_test_status
from webapp.views.error import error_view, instruction

app_name = 'webapp'

urlpatterns = [
    path('', MainListView.as_view(), name='main_page'),
    path('access_denied/', error_view, name='error_page'),
    path('instruction/', instruction, name='instruction'),
    # users-url -----------------------------------------------------------------------------------------------
    path('register/', register, name='register'),
    path('users_list/', UserListView.as_view(), name='users_list'),
    path('user/<int:pk>/detail/', UserDetailView.as_view(), name='user_detail'),
    path('user/<int:u_pk>/update/', user_update, name='user_update'),
    path('user/<int:pk>/delete/', soft_delete_user, name='user_delete'),
    path('user/<int:pk>/password_change/', user_password_update, name='password_update'),
    # counter urls------------------------------------------------------------------------------------------------
    path('skill_w_hint/<int:pk>', counter_done_with_hint, name='done_w_hint'),
    path('skill_done/<int:pk>', counter_done, name='counter_done'),
    path('get_skills/<int:pk>', counter_get_view, name='counter_get_view'),
    # child urls--------------------------------------------------------------------------------------------------
    path('child/', ChildList.as_view(), name='child_list'),
    path('child_search/', ChildSearchView.as_view(), name='search_view'),
    path('child/<int:pk>', ChildDetailView.as_view(), name='child_detail'),
    path('child/create', ChildCreateView.as_view(), name='child_create'),
    path('child/<int:pk>/update', ChildUpdateView.as_view(), name='child_update'),
    path('child/<int:pk>/delete', soft_delete_child, name='child_delete'),
    # program urls------------------------------------------------------------------------------------------------
    path('program/', ProgramListView.as_view(), name='program_list'),
    path('program_search/', ProgramSearchView.as_view(), name='search_view_program'),
    path('program/<int:pk>', ProgramDetailView.as_view(), name='program_detail'),
    path('program/create', ProgramCreateView.as_view(), name='program_create'),
    path('program/<int:pk>/update', ProgramUpdateView.as_view(), name='program_update'),
    path('program/<int:pk>/create', AddSkillInProgram.as_view(), name='program_skill_add'),
    path('program/<int:program_pk>/skill/<int:pk>/update/', SkillInProgramUpdate.as_view(),
         name='program_skill_update'),
    path('program/<int:pk>/delete', soft_delete_program, name='program_delete'),
    # category urls-----------------------------------------------------------------------------------------------
    path('categories/', CategoriesListView.as_view(), name='categories_list'),
    path('categories/<int:pk>', CategoriesDetailView.as_view(), name='categories_detail'),
    path('categories/create', CategoriesCreateView.as_view(), name='categories_create'),
    path('categories/<int:pk>/update', CategoriesUpdateView.as_view(), name='categories_update'),
    path('categories/categories_search/', CategoriesSearchView.as_view(), name='search_view_categories'),
    # session_urls------------------------------------------------------------------------------------------------
    path('program/<int:pk>/session', create_session_and_result, name='session_create'),
    # path('program/<int:pk>/skill/create', AddExtraSkill.as_view(), name='extra_skill'),
    path('session/<int:pk>/cancel', cancel_session, name='cancel_session'),
    # result_urls------------------------------------------------------------------------------------------------
    path('session/<int:pk>/result', ResultListView.as_view(), name='session_result_view'),
    path('session/<int:pk>', close_session_result_view, name='change_status_session'),
    path('skill_in_program/<int:pk>', change_status_skill, name='change_status_skill'),
    # skill urls--------------------------------------------------------------------------------------------------
    path('skill/<int:pk>', SkillDetailView.as_view(), name='skill_detail'),
    path('skill/create', SkillCreateView.as_view(), name='skill_create'),
    path('skill/<int:pk>/update', SkillUpdateView.as_view(), name='skill_update'),
    path('skill/<int:pk>/delete', delete_skill, name='skill_delete'),
    path('skill/skill_search/', SkillSearchView.as_view(), name='search_view_skill'),
    path('skill/skill_search/', SkillSearchView.as_view(), name='search_view_skill'),
    # testing urls--------------------------------------------------------------------------------------------------
    path('child/<int:child_pk>/create_test', CreateTesting.as_view(), name='create_testing'),
    path('child/<int:child_pk>/test/<int:test_pk>', StartTesting.as_view(), name='start_testing'),
    path('test/<int:pk>', update_result_level, name='update_level'),
    path('change_result_status/<int:pk>', update_result_status, name='update_result_status'),
    path('change_test_status/<int:pk>', update_test_status, name='update_test_status'),
    # import word_and_excel---------------------------------------------------------------------------------------------
    path('create_excel/<int:program_pk>', create_excel_file, name='create_excel'),
    path('create_homework/<int:program_pk>', create_word_homework, name='create_homework'),
    path('create_program/<int:program_pk>', create_word_program, name='create_program'),
]

source/webapp/models.py
from django.db import models
from django.contrib.auth.models import User


class UserInfo(models.Model):
    user = models.OneToOneField(User, on_delete=models.PROTECT, related_name='client', verbose_name='Пользователь')
    phone = models.CharField(max_length=50, null=False, blank=False, verbose_name='Телефон пользователя')
    child = models.ManyToManyField('Child', through='UsersChild', blank=True, related_name='user_child',
                                   verbose_name='Ребенок')
    deleted_date = models.DateTimeField(null=True, blank=True, verbose_name='Дата удаления')
    edited_date = models.DateTimeField(auto_now=True, blank=True, null=True, verbose_name='Дата редактирования')

    def __str__(self):
        return "%s" % self.user.username


class SoftDeleteManager(models.Manager):
    def active(self):
        return self.filter(is_deleted=False)

    def deleted(self):
        return self.filter(is_deleted=True)


class Child(models.Model):
    first_name = models.CharField(max_length=100, verbose_name='Имя ребенка')
    last_name = models.CharField(max_length=100, verbose_name='Фамилия ребенка')
    third_name = models.CharField(max_length=100, blank=True, null=True, verbose_name='Отчество ребенка')
    birthday = models.DateField(blank=True, null=True, verbose_name='Дата рождения')
    age = models.CharField(max_length=100, verbose_name='Возраст')
    address = models.TextField(max_length=1000, blank=True, null=True, verbose_name='Адрес проживания')
    characteristic = models.CharField(max_length=1000, blank=True, null=True, verbose_name='Характеристика на ребенка')
    preferences = models.CharField(max_length=1000, blank=True, null=True, verbose_name='Предпочтения ребенка')
    first_parent = models.CharField(max_length=255, verbose_name='Родитель')
    second_parent = models.CharField(max_length=255, blank=True, null=True, verbose_name='Второй родитель')
    contacts = models.CharField(max_length=200, blank=True, null=True, verbose_name='Контакты ребенка')
    created_date = models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления ребенка')
    edited_date = models.DateTimeField(auto_now=True, null=True, blank=True, verbose_name='Дата редактирования')
    deleted_date = models.DateTimeField(null=True, blank=True, verbose_name='Дата удаления')
    communication_system = models.TextField(max_length=1000, blank=True, null=True, verbose_name='Система коммуникации')
    is_deleted = models.BooleanField(default=False)

    objects = SoftDeleteManager()

    def __str__(self):
        return "%s %s" % (self.first_name, self.last_name)

    class Meta:
        verbose_name = 'Дети'
        verbose_name_plural = 'Дети'


class UsersChild(models.Model):
    user = models.ForeignKey(UserInfo, related_name='related_to_user', on_delete=models.CASCADE,
                             verbose_name='Пользователь')
    child = models.ForeignKey(Child, null=True, blank=True, related_name='child_in_user', on_delete=models.CASCADE,
                              verbose_name='Ребенок')

    def __str__(self):
        return self.user.user.username

    class Meta:
        verbose_name = 'Дети пользователя'
        verbose_name_plural = 'Дети пользователей'


class Categories(models.Model):
    name = models.CharField(max_length=255, verbose_name='Название секции')
    code_category = models.CharField(max_length=50, verbose_name='Код секции')
    created_date = models.DateTimeField(auto_now_add=True, verbose_name='Время добавления')
    edited_date = models.DateTimeField(auto_now=True, null=True, blank=True, verbose_name='Время редактирования')
    deleted_date = models.DateTimeField(null=True, blank=True, verbose_name='Время удаления')
    is_deleted = models.BooleanField(default=False)

    objects = SoftDeleteManager()

    def __str__(self):
        return "%s. %s" % (self.code_category, self.name)

    class Meta:
        verbose_name = 'Секция'
        verbose_name_plural = 'Секции'


class Skill(models.Model):
    code_skill = models.CharField(max_length=5, verbose_name='Код навыка')
    name = models.CharField(max_length=255, verbose_name='Название навыка')
    skill_comment = models.CharField(max_length=255, null=True, blank=True, verbose_name='Комментарий к навыку')
    category = models.ForeignKey(Categories, on_delete=models.PROTECT, related_name='skill', verbose_name='Секция')
    description = models.TextField(max_length=1000, null=True, blank=True, verbose_name='Описание навыка')
    criterion = models.TextField(max_length=1000, null=True, blank=True, verbose_name='Критерии')
    difficulty = models.PositiveSmallIntegerField(default=1, verbose_name="Количество уровней сложности")
    created_date = models.DateTimeField(auto_now_add=True, verbose_name='Время создания навыка')
    updated_date = models.DateTimeField(auto_now=True, null=True, blank=True,
                                        verbose_name='Время редактирование навыка')
    deleted_date = models.DateTimeField(null=True, blank=True, verbose_name='Время удаления навыка')

    def __str__(self):
        return "%s. %s" % (self.code_skill, self.name)

    class Meta:
        verbose_name = 'Навык'
        verbose_name_plural = 'Навыки'


class SkillsInProgram(models.Model):
    program = models.ForeignKey('Program', related_name='related_to_program', on_delete=models.PROTECT,
                                verbose_name='Программа')
    skill = models.ForeignKey('Skill', null=True, blank=True, related_name='skill_in_program', on_delete=models.CASCADE,
                              verbose_name='Навык')
    added_skill = models.CharField(max_length=1000,
                                   verbose_name='Добавленный навык', null=True,
                                   blank=True)
    added_skill_comment = models.CharField(max_length=255, null=True, blank=True,
                                           verbose_name='Комментарий к добавленному навыку')
    extra_skill_to_skill = models.ForeignKey('SkillsInProgram', related_name='extra_skill_in_program',
                                             on_delete=models.PROTECT,
                                             null=True, blank=True, verbose_name='Поднавык')
    mastery_criterion = models.CharField(max_length=255, null=True, blank=True, verbose_name='Критерий мастерства')
    stimulus = models.TextField(max_length=1000, null=True, blank=True, verbose_name='Стимул')
    study_method = models.ForeignKey('StudyMethod', on_delete=models.PROTECT, max_length=255, null=True, blank=True,
                                     verbose_name='Метод обучения')
    reinforcement_reaction = models.CharField(max_length=255, null=True, blank=True,
                                              verbose_name='Реакция для подкрепления')
    reinforcement_mode = models.CharField(max_length=255, null=True, blank=True, verbose_name='Режим подкрепления')
    hint_type = models.ForeignKey('HintType', on_delete=models.PROTECT, max_length=255, null=True, blank=True,
                                  verbose_name='Вид подсказки')
    hint_type_delete = models.ForeignKey('HintTypeDelete', on_delete=models.PROTECT, max_length=255, null=True,
                                         blank=True, verbose_name='Способ удаления подсказки')
    hint_levels = models.CharField(max_length=255, null=True, blank=True, verbose_name='Уровень подсказки')
    generalization = models.CharField(max_length=500, null=True, blank=True, verbose_name='Обобщение')
    reaction_generalization = models.CharField(max_length=500, null=True, blank=True, verbose_name='Обобщение реакции')
    stimulus_generalization = models.CharField(max_length=500, null=True, blank=True, verbose_name='Обобщение стимула')
    status = models.BooleanField(default=True, verbose_name='Статус')

    def __str__(self):
        return "Навык %s, программа %s" % (self.id, self.program.name)

    class Meta:
        verbose_name = 'Навык в программе'
        verbose_name_plural = 'Навыки в программе'


class Program(models.Model):
    name = models.CharField(max_length=255, null=True, blank=True, verbose_name="Название программы")
    description = models.TextField(max_length=2000, blank=True, null=True, verbose_name="Описание программы")
    program_comment = models.CharField(max_length=255, null=True, blank=True, verbose_name='Комментарий к программе')
    child = models.ForeignKey('Child', on_delete=models.PROTECT, related_name='child_in_program',
                              verbose_name='Ребенок')
    author_therapist = models.ForeignKey(UserInfo, on_delete=models.PROTECT, related_name='author_program',
                                         verbose_name='Терапист')
    skills = models.ManyToManyField('Skill', through='SkillsInProgram', blank=True, verbose_name='Навыки')
    status = models.BooleanField(default=True, verbose_name='Статус')
    created_date = models.DateTimeField(auto_now_add=True, verbose_name="Дата создания")
    edited_date = models.DateTimeField(auto_now=True, blank=True, null=True, verbose_name="Дата редактирования")
    deleted_date = models.DateTimeField(blank=True, null=True, verbose_name="Дата удаления")
    is_deleted = models.BooleanField(default=False)

    objects = SoftDeleteManager()

    def __str__(self):
        return "%s %s - программа №%s" % (self.child.first_name, self.child.last_name, self.id)

    class Meta:
        verbose_name = 'Программа'
        verbose_name_plural = 'Программы'


class Session(models.Model):
    program = models.ForeignKey(Program, related_name='session_program', on_delete=models.PROTECT,
                                verbose_name='Программа')
    attending_therapist = models.ForeignKey(UserInfo, on_delete=models.PROTECT, null=True,
                                            related_name='attending_session')  # сделал временно null
    description = models.TextField(max_length=2000, blank=True, null=True, verbose_name="Описание сессии")

source/webapp/templates/child_views/child_create.html
{% extends 'base.html' %}
{% block title %}Создание профиля ребёнка{% endblock %}
{% block content %}
    <div class="container">
        <h2 class="mb-4">Добавление профиля ребёнка</h2>
        <form action="{% url 'webapp:child_create' %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="form-group row was-validated">
                <label for="id_first_name" class="col-sm-2 col-form-label col-form-label-sm">Имя
                    ребенка:</label>
                <div class="col-sm-6">
                    {{ form.first_name }}
                    <small class="form-text text-muted">Обязательное поле</small>
                    {% for i in form.first_name.errors %}
                        <p class="font-weight-light text-danger d-block small text-center pb-0 mb-0">{{ i }}</p>
                    {% endfor %}
                </div>
            </div>
            <div class="form-group row was-validated">
                {{ form.last_name.errors }}
                <label for="id_last_name" class="col-sm-2 col-form-label col-form-label-sm">Фамилия ребенка:</label>
                <div class="col-sm-6">
                    {{ form.last_name }}
                    <small class="form-text text-muted">Обязательное поле</small>
                    {% for i in form.last_name.errors %}
                        <p class="font-weight-light text-danger d-block small text-center pb-0 mb-0">{{ i }}</p>
                    {% endfor %}
                </div>
            </div>
            <div class="form-group row">
                <label for="id_third_name" class="col-sm-2 col-form-label col-form-label-sm">Отчество ребенка:</label>
                <div class="col-sm-6">
                    {{ form.third_name }}
                    {% for i in form.third_name.errors %}
                        <p class="font-weight-light text-danger d-block small text-center pb-0 mb-0">{{ i }}</p>
                    {% endfor %}

                </div>
            </div>
            <div class="form-group row">
                <label for="id_birthday" class="col-sm-2 col-form-label col-form-label-sm">Дата рождения.</label>
                <div class="col-sm-6">
                    {{ form.birthday }}
                    {% for i in form.birthday.errors %}
                        <p class="font-weight-light text-danger d-block small text-center pb-0 mb-0">{{ i }}</p>
                    {% endfor %}
                </div>
            </div>
            <div class="form-group row was-validated">
                <label for="id_age" class="col-sm-2 col-form-label col-form-label-sm">Возраст:</label>
                <div class="col-sm-6">
                    {{ form.age }}
                    <small class="form-text text-muted">Обязательное поле</small>
                    {% for i in form.age.errors %}
                        <p class="font-weight-light text-danger d-block small text-center pb-0 mb-0">{{ i }}</p>
                    {% endfor %}
                </div>
            </div>
            <div class="form-group row">
                <label for="id_address" class="col-sm-2 col-form-label col-form-label-sm">Адрес:</label>
                <div class="col-sm-6">
                    {{ form.address }}
                    {% for i in form.address.errors %}
                        <p class="font-weight-light text-danger d-block small text-center pb-0 mb-0">{{ i }}</p>
                    {% endfor %}
                </div>
            </div>
            <div class="form-group row">
                <label for="id_characteristic" class="col-sm-2 col-form-label col-form-label-sm">Характеристика:</label>
                <div class="col-sm-6">
                    {{ form.characteristic }}
                    {% for i in form.characteristic.errors %}
                        <p class="font-weight-light text-danger d-block small text-center pb-0 mb-0">{{ i }}</p>
                    {% endfor %}
                </div>
            </div>
            <div class="form-group row">
                <label for="id_preferences" class="col-sm-2 col-form-label col-form-label-sm">Предпочтения:</label>
                <div class="col-sm-6">
                    {{ form.preferences }}
                    {% for i in form.preferences.errors %}
                        <p class="font-weight-light text-danger d-block small text-center pb-0 mb-0">{{ i }}</p>
                    {% endfor %}
                </div>
            </div>
            <div class="form-group row">
                <label for="id_communication_system" class="col-sm-2 col-form-label col-form-label-sm">Система коммуникации:</label>
                <div class="col-sm-6">
                    {{ form.communication_system }}
                    {% for i in form.communication_system.errors %}
                        <p class="font-weight-light text-danger d-block small text-center pb-0 mb-0">{{ i }}</p>
                    {% endfor %}
                </div>
            </div>
            <div class="form-group row was-validated">
                <label for="id_first_parent" class="col-sm-2 col-form-label col-form-label-sm">Первый родитель:</label>
                <div class="col-sm-6">
                    {{ form.first_parent }}
                    <small class="form-text text-muted">Обязательное поле</small>
                </div>
            </div>
            <div class="form-group row">
                <label for="id_second_parent" class="col-sm-2 col-form-label col-form-label-sm">Второй родитель:</label>
                <div class="col-sm-6">
                    {{ form.second_parent }}
                    {% for i in form.first_pasecond_parentrent.errors %}
                        <p class="font-weight-light text-danger d-block small text-center pb-0 mb-0">{{ i }}</p>
                    {% endfor %}
                </div>
            </div>
            <div class="form-group row">
                <label for="id_contacts" class="col-sm-2 col-form-label col-form-label-sm">Контакты:</label>
                <div class="col-sm-6 input-group">
                    <div class="input-group-prepend">
                        <div class="input-group-text"><i class="fas fa-phone"></i></div>
                    </div>
                    {{ form.contacts }}
                    {% for i in form.contacts.errors %}
                        <p class="font-weight-light text-danger d-block small text-center pb-0 mb-0">{{ i }}</p>
                    {% endfor %}
                </div>
            </div>
            <button type="submit" class="btn btn-primary p-1" id="add_child_button" style="width: 70px;">Добавить
            </button>
            <a role="button" class="btn btn-primary p-1" href="{% url 'webapp:child_list' %}"
               style="width: 70px;">Назад</a>
        </form>
    </div>
{% endblock %}

source/webapp/templates/child_views/child_update.html
{% extends 'base.html' %}
{% block title %}Редактирование ребёнка{% endblock %}
{% block content %}
    <div class="container">
        <h2 class="text-center">Редактирование данных ребенка</h2>
        <form action="{% url 'webapp:child_update' form.instance.pk %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="form-group row was-validated">
                <label for="id_first_name" class="col-sm-2 col-form-label col-form-label-sm">Имя
                    ребенка:</label>
                <div class="col-sm-6">
                    {{ form.first_name }}
                    <small class="form-text text-muted">Обязательное поле</small>
                    {% for i in form.first_name.errors %}
                        <p class="font-weight-light text-danger d-block small text-center pb-0 mb-0">{{ i }}</p>
                    {% endfor %}
                </div>
            </div>
            <div class="form-group row was-validated">
                {{ form.last_name.errors }}
                <label for="id_last_name" class="col-sm-2 col-form-label col-form-label-sm">Фамилия ребенка:</label>
                <div class="col-sm-6">
                    {{ form.last_name }}
                    <small class="form-text text-muted">Обязательное поле</small>
                    {% for i in form.last_name.errors %}
                        <p class="font-weight-light text-danger d-block small text-center pb-0 mb-0">{{ i }}</p>
                    {% endfor %}
                </div>
            </div>
            <div class="form-group row">
                <label for="id_third_name" class="col-sm-2 col-form-label col-form-label-sm">Отчество ребенка:</label>
                <div class="col-sm-6">
                    {{ form.third_name }}
                    {% for i in form.third_name.errors %}
                        <p class="font-weight-light text-danger d-block small text-center pb-0 mb-0">{{ i }}</p>
                    {% endfor %}

                </div>
            </div>
            <div class="form-group row">
                <label for="id_birthday" class="col-sm-2 col-form-label col-form-label-sm">Дата рождения.</label>
                <div class="col-sm-6">
                    {{ form.birthday }}
                    {% for i in form.birthday.errors %}
                        <p class="font-weight-light text-danger d-block small text-center pb-0 mb-0">{{ i }}</p>
                    {% endfor %}
                </div>
            </div>
            <div class="form-group row was-validated">
                <label for="id_age" class="col-sm-2 col-form-label col-form-label-sm">Возраст:</label>
                <div class="col-sm-6">
                    {{ form.age }}
                    <small class="form-text text-muted">Обязательное поле</small>
                    {% for i in form.age.errors %}
                        <p class="font-weight-light text-danger d-block small text-center pb-0 mb-0">{{ i }}</p>
                    {% endfor %}
                </div>
            </div>
            <div class="form-group row">
                <label for="id_address" class="col-sm-2 col-form-label col-form-label-sm">Адрес:</label>
                <div class="col-sm-6">
                    {{ form.address }}
                    {% for i in form.address.errors %}
                        <p class="font-weight-light text-danger d-block small text-center pb-0 mb-0">{{ i }}</p>
                    {% endfor %}
                </div>
            </div>
            <div class="form-group row">
                <label for="id_characteristic" class="col-sm-2 col-form-label col-form-label-sm">Характеристика:</label>
                <div class="col-sm-6">
                    {{ form.characteristic }}
                    {% for i in form.characteristic.errors %}
                        <p class="font-weight-light text-danger d-block small text-center pb-0 mb-0">{{ i }}</p>
                    {% endfor %}
                </div>
            </div>
            <div class="form-group row">
                <label for="id_preferences" class="col-sm-2 col-form-label col-form-label-sm">Предпочтения:</label>
                <div class="col-sm-6">
                    {{ form.preferences }}
                    {% for i in form.preferences.errors %}
                        <p class="font-weight-light text-danger d-block small text-center pb-0 mb-0">{{ i }}</p>
                    {% endfor %}
                </div>
            </div>
            <div class="form-group row">
                <label for="id_communication_system" class="col-sm-2 col-form-label col-form-label-sm">Система коммуникации:</label>
                <div class="col-sm-6">
                    {{ form.communication_system }}
                    {% for i in form.communication_system.errors %}
                        <p class="font-weight-light text-danger d-block small text-center pb-0 mb-0">{{ i }}</p>
                    {% endfor %}
                </div>
            </div>
            <div class="form-group row was-validated">
                <label for="id_first_parent" class="col-sm-2 col-form-label col-form-label-sm">Первый родитель:</label>
                <div class="col-sm-6">
                    {{ form.first_parent }}
                    <small class="form-text text-muted">Обязательное поле</small>
                </div>
            </div>
            <div class="form-group row">
                <label for="id_second_parent" class="col-sm-2 col-form-label col-form-label-sm">Второй родитель:</label>
                <div class="col-sm-6">
                    {{ form.second_parent }}
                    {% for i in form.first_pasecond_parentrent.errors %}
                        <p class="font-weight-light text-danger d-block small text-center pb-0 mb-0">{{ i }}</p>
                    {% endfor %}
                </div>
            </div>
            <div class="form-group row">
                <label for="id_contacts" class="col-sm-2 col-form-label col-form-label-sm">Контакты:</label>
                <div class="col-sm-6 input-group">
                    <div class="input-group-prepend">
                        <div class="input-group-text"><i class="fas fa-phone"></i></div>
                    </div>
                    {{ form.contacts }}
                    {% for i in form.contacts.errors %}
                        <p class="font-weight-light text-danger d-block small text-center pb-0 mb-0">{{ i }}</p>
                    {% endfor %}
                </div>
            </div>
            <button type="submit" class="btn btn-success m-2" style="width: 125px">Сохранить</button>
            <a role="button" class="btn btn-primary m-2" href="{{ request.META.HTTP_REFERER }}"
               style="width: 125px">Назад</a>
        </form>
    </div>
{% endblock %}